import type { DataStore } from "./types";

export const INITIAL_DATA: DataStore = {
  builders: [
    { id: "bld_prestige", name: "Prestige Estates", slug: "prestige" },
  ],
  users: [
    {
      id: "usr_admin",
      email: "admin@prestige.demo",
      password: "admin123",
      name: "Priya Sharma",
      role: "admin",
      builderId: "bld_prestige",
    },
    {
      id: "usr_sales",
      email: "sales@prestige.demo",
      password: "sales123",
      name: "Rahul Mehta",
      role: "sales",
      builderId: "bld_prestige",
    },
    {
      id: "usr_docs",
      email: "docs@prestige.demo",
      password: "docs123",
      name: "Anita Desai",
      role: "document_manager",
      builderId: "bld_prestige",
    },
  ],
  customers: [
    {
      id: "cust_001",
      builderId: "bld_prestige",
      name: "Vikram Patel",
      phone: "+919876543210",
      email: "vikram.patel@email.com",
      unit: "4B",
      tower: "Tower 2",
      project: "Prestige Lakeside Habitat",
    },
    {
      id: "cust_002",
      builderId: "bld_prestige",
      name: "Sneha Reddy",
      phone: "+919123456789",
      email: "sneha.reddy@email.com",
      unit: "12A",
      tower: "Tower 1",
      project: "Prestige Lakeside Habitat",
    },
    {
      id: "cust_003",
      builderId: "bld_prestige",
      name: "Arjun Nair",
      phone: "+919988776655",
      unit: "7C",
      tower: "Tower 3",
      project: "Prestige Suncrest",
    },
  ],
  documents: [
    {
      id: "doc_001",
      customerId: "cust_001",
      builderId: "bld_prestige",
      type: "sale_agreement",
      title: "Sale Agreement",
      fileName: "sale-agreement-vikram-4b.pdf",
      filePath: "/uploads/sample-sale-agreement.pdf",
      mimeType: "application/pdf",
      visibility: "customer",
      documentDate: "2025-01-12",
      uploadedBy: "Anita Desai",
      uploadedAt: "2025-01-15T10:30:00Z",
    },
    {
      id: "doc_002",
      customerId: "cust_001",
      builderId: "bld_prestige",
      type: "price_breakup",
      title: "Price Breakup Letter",
      fileName: "price-breakup-vikram.pdf",
      filePath: "/uploads/sample-price-breakup.pdf",
      mimeType: "application/pdf",
      visibility: "customer",
      documentDate: "2025-01-10",
      uploadedBy: "Anita Desai",
      uploadedAt: "2025-01-14T09:00:00Z",
    },
    {
      id: "doc_003",
      customerId: "cust_001",
      builderId: "bld_prestige",
      type: "allotment_letter",
      title: "Allotment Letter",
      fileName: "allotment-vikram.pdf",
      filePath: "/uploads/sample-allotment.pdf",
      mimeType: "application/pdf",
      visibility: "customer",
      documentDate: "2024-11-20",
      uploadedBy: "Anita Desai",
      uploadedAt: "2024-11-22T14:00:00Z",
    },
    {
      id: "doc_004",
      customerId: "cust_001",
      builderId: "bld_prestige",
      type: "payment_receipt",
      title: "Payment Receipt — Booking",
      fileName: "receipt-booking-internal.pdf",
      filePath: "/uploads/sample-receipt.pdf",
      mimeType: "application/pdf",
      visibility: "internal",
      documentDate: "2024-10-05",
      uploadedBy: "Rahul Mehta",
      uploadedAt: "2024-10-05T16:00:00Z",
    },
    {
      id: "doc_005",
      customerId: "cust_002",
      builderId: "bld_prestige",
      type: "sale_agreement",
      title: "Sale Agreement",
      fileName: "sale-agreement-sneha.pdf",
      filePath: "/uploads/sample-sale-agreement.pdf",
      mimeType: "application/pdf",
      visibility: "customer",
      documentDate: "2025-02-01",
      uploadedBy: "Anita Desai",
      uploadedAt: "2025-02-03T11:00:00Z",
    },
  ],
  audit: [
    {
      id: "aud_seed_1",
      builderId: "bld_prestige",
      action: "document.uploaded",
      actor: "Anita Desai",
      actorType: "portal_user",
      customerId: "cust_001",
      documentId: "doc_001",
      metadata: { type: "sale_agreement" },
      createdAt: "2025-01-15T10:30:00Z",
    },
  ],
};
